#!/usr/bin/env python3
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)
from datetime import datetime, timedelta
import os
import re

# start of an algorithm
algdeclare = re.compile(r'^Algorithm:\s+(.+)\s+v(\d+)$')
algstart = re.compile(r'^Execution Date:\s+(.+)$')
algparam = re.compile(r'^Name:\s+(.+),\s+Value:\s+(.*),\s+Default\?:\s+(.+),.+$')

# Example: 2016-Sep-21 13:26:18
timeformat = '%Y-%b-%d %H:%M:%S'
delta_default = '?:??:??'

class Property:
    def __init__(self, line):
        match = algparam.match(line)
        self.name = match.group(1)
        self.value = match.group(2)
        self.isDefault = match.group(3)
        if self.isDefault == 'Yes':
            self.isDefault = True
        else:
            self.isDefault = False

    def __str__(self):
        if self.isDefault:
            return ''
        else:
            return '%s=\'%s\'' % (self.name, self.value)

class Algorithm:
    def __init__(self, lines):
        match = algdeclare.match(lines[0])
        self.name = match.group(1)
        self.version = match.group(2)
        match = algstart.match(lines[1])
        self.startdate = datetime.strptime(match.group(1), timeformat)
        self.props = []
        for line in lines[2:]:
            self.props.append(Property(line))
        self.delta = delta_default

    def full(self):
        params = [str(param) for param in self.props if not param.isDefault]
        return self.name+'(' + ', '.join(params) + ')'

    def minimal(self):
        params = [param for param in self.props if not param.isDefault]

        allowed = ['InputWorkspace', 'Workspace', 'Filename',
                   'RHSWorkspace', 'LHSWorkspace']
        params = [param for param in params if param.name in allowed]
        params = [str(param) for param in params]

        #if len(params) > 1:
        #    params = [params[0]]

        if len(params) != len(self.props):
            params.append('...')

        return self.name+'(' + ', '.join(params) + ')'

def parseLog(filename):
    print('parsing', filename)

    # proper log line
    logline = re.compile(r'^(.+)-\[(Information|Notice|Warning|Error)\]\s+(.+)')

    algorithms = []

    with open(filename, 'r') as handle:
        alglines = []
        for line in handle:
            line = line.strip()
            match = logline.match(line)
            if match:
                stuff = match.group(3).strip()
                if algdeclare.match(stuff):
                    if len(alglines) > 0:
                        algorithms.append(Algorithm(alglines))
                    alglines = [stuff]
                elif algstart.match(stuff):
                    alglines.append(stuff)
                elif algparam.match(stuff):
                    alglines.append(stuff)
                elif stuff in ['Parameters:',
                               'Execution Duration: -1 seconds']:
                    pass
                elif ' successful, Duration ' in stuff:
                    pass
                else:
                    pass
                    #print("fell through:", stuff)
        if len(alglines) > 0:
            algorithms.append(Algorithm(alglines))

    return algorithms

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description='Get timing and information of a reduction log')
    parser.add_argument('file',
                        help='Log file to parse')

    args=parser.parse_args()
    args.file = os.path.abspath(args.file)

    data = parseLog(args.file)

    # calculate execution time
    for i in range(len(data)-1):
        data[i].delta = data[i+1].startdate - data[i].startdate

    # print the details
    long = []
    for item in data:
        if item.delta != delta_default and item.delta > timedelta(minutes=1):
            long.append(item)
        print(item.startdate.strftime('%H:%M:%S'), '---', item.delta,
              '---', item.minimal())


    if len(long) > 0:
        print('-------- Long running algorithms',
              '----------------------------------------------')
        for item in long:
            print(item.startdate.strftime('%H:%M:%S'), '---', item.delta,
                  '---', item.full())
